version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbitMQ"
    ports:
      - "15672:15672"
      - "5672:5672"
